# Generated by Django 4.2 on 2023-04-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
