# Generated by Django 4.2 on 2023-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='oder_date',
            field=models.DateField(default=''),
        ),
    ]
