# Generated by Django 4.2 on 2023-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_orders_oder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_size',
            field=models.CharField(default='', max_length=5),
        ),
    ]
