# Generated by Django 4.2 on 2023-04-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_orders_oder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='oder_date',
        ),
    ]
