# Generated by Django 4.2 on 2023-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_orders_oder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_size',
            field=models.CharField(default='Small', max_length=5),
        ),
    ]
