# Generated by Django 4.2 on 2023-04-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_cart_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='oder_date',
        ),
    ]
