# Generated by Django 4.2 on 2023-04-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_remove_orders_oder_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
