# Generated by Django 4.2 on 2023-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=20)),
                ('user_items_final', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_size',
        ),
    ]
