# Generated by Django 4.2 on 2023-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_orders_remove_cart_item_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_size',
            field=models.CharField(default='Small', max_length=5),
        ),
    ]
