# Generated by Django 4.2 on 2023-04-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_delete_orders_cart_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_address',
            field=models.CharField(default='N/A', max_length=70),
        ),
    ]
