# Generated by Django 4.2 on 2023-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_alter_address_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_pincode',
            field=models.IntegerField(default=0),
        ),
    ]
