# Generated by Django 4.2 on 2023-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_address_user_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=20)),
                ('user_item', models.CharField(max_length=20)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_size', models.CharField(max_length=9)),
                ('date', models.CharField(max_length=20)),
                ('user_total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_size',
            field=models.CharField(default='Small', max_length=9),
        ),
    ]
