# Generated by Django 4.2 on 2023-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_size',
            field=models.CharField(max_length=9),
        ),
    ]
